package exceptionHandling;
/*
 * With one try block we can have multiple catch blocks
 */
public class MultipleCatch {

	public static void main(String[] args) {
	
		try {}
		catch(ArithmeticException e) {}
		catch(ArrayIndexOutOfBoundsException e) {}
	}

}
